### ISSUE TITLE
Anti-virus false positive

### ISSUE THREAD

**Issue by isaacwhanson** [starlight/swan-desktop#1]
[The_Cave_Troll](https://www.reddit.com/user/The_Cave_Troll) said:  

> Anti-virus is convinced that "C:\lux-x86_64\bin\dbus-daemon.exe" is some sort of malware, and I had to add it to my exception list. But Lux still doesn't start, not until I disable my anti-virus (which is AVG 2016).

**Comment by isaacwhanson** [comment]
submitted the dbus-daemon.exe file to AVG.  there seems to be a lot of issues with AVG.  adding the root cygwin-folder to the exception list seems to be a workaround.

**Comment by IanCass** [comment]
Symantec won't allow install either

**Comment by isaacwhanson** [comment]
It has been submitted to AVG, Symantec, and others.  They have whitelisted the program, but when the files change in the future, they may no longer be recognized as safe.
