### ISSUE TITLE
Installer proxy settings 

### ISSUE THREAD

**Issue by ZeppelinPL** [starlight/swan-desktop#10]
Is there any way to set http proxy setting for the installer? If not can you consider introducing one?

Regards,
Krzysztof.

**Comment by isaacwhanson** [comment]
I will look into this further.

**Comment by Rycieos** [comment]
For the installer, you can download the Cygwin installer and run the command that the custom installer is running, minus the "no GUI" flag (-q). You can see that command in the [installer source](https://github.com/starlight/swan-base/blob/master/SwanSetup.nsi).

This is an interesting question concerning the package manager.

**Comment by isaacwhanson** [comment]
I can probably put an option in the installer for that.

**Comment by Thracky** [comment]
Might make sense to more fully support the OS proxy settings using something like [Inetc ](http://nsis.sourceforge.net/Inetc_plug-in) instead of NSISdl?

**Comment by isaacwhanson** [comment]
This should be fixed now.  Let me know if it doesn't work for you, @ZeppelinPL 

Thanks for the solution @Thracky
