### ISSUE TITLE
MSYS2

### ISSUE THREAD

**Issue by oysteinkrog** [starlight/swan-desktop#13]
Hi,

Have you seen MSYS2?
It would be awesome if this was based on MSYS2 instead of just cygwin :)

**Comment by isaacwhanson** [comment]
Hadn't looked at MSYS2 in a while.  I will look into that, wouldn't mind having a more Arch-like environment.

**Comment by gfody** [comment]
MSYS2 isn't really for this sort of thing - see [MSYS2 vs. Cygwin](https://github.com/msys2/msys2/wiki/How-does-MSYS2-differ-from-Cygwin), basically Cygwin is for running UNIX software on Windows and so comes with all the requisite heft. MSYS2 is a deliberately minimal build environment. The "MSYS2 way" would be to create a mingw build packages for xfce4-appfinder and/or whatever other standalone apps make sense - i.e.: compile native Windows binaries of various xfce4 apps, not just render to a local X server.
