### ISSUE TITLE
Internal compositing window manager

### ISSUE THREAD

**Issue by aaronfranke** [starlight/swan-desktop#15]
Feature request: Change the window manager to a compositing one. Many things don't work in this current non-compositing window manager. For example, `xfce4-panel` and notifications can't be transparent.

**Comment by isaacwhanson** [comment]
You can turn compositing on by adding the `-compositealpha` flag to X in `/etc/X11/xinit/xserverrc`.

I don't have it on, because it blurs the shadows on xfce4-terminal in a weird way.  I have been playing around with it, and if you can get a good-looking setup, let me know.
