### ISSUE TITLE
Improvement - Bundle Terminator

### ISSUE THREAD

**Issue by iongion** [starlight/swan-desktop#24]
I understand this project revolves around xfce, but supporting Terminator by default would be an awesome feature.
Terminator is not easy to compile and launch for a normal user, not even for a developer.
This, together with the ability to use switch to WSL from cygwin(but also keeping cygwin), would create an awesome development environment.
In any way, I like this project very much, great achievement!

**Comment by iongion** [comment]
Apparently, it is very easy to have terminator:

`spm -i terminator`

Disregard my previous request, I see terminator needs the entire Gnome world!
It works just fine after installing it using spm, but the fonts are much more beautiful in the default xfce terminal:

![image](https://cloud.githubusercontent.com/assets/867609/24397199/d0fa1d16-13a5-11e7-9029-ca709b7adc8b.png)

I preffer *swan* light, as it is right now, but can something be done to have pretty, antialiased fonts for terminator too ?

**Comment by isaacwhanson** [comment]
Maybe try setting the font on terminator to "iosevka term". This is the optimized terminal font used in Xfce terminal. It has good antialias features.
