### ISSUE TITLE
SwanSetup.exe flagged as malware

### ISSUE THREAD

**Issue by rogierg** [starlight/swan-desktop#27]
Hi there,

Not sure why this happens, could be a false positive.

See: https://virustotal.com/en/file/ac1446aca41ca31dd701f8ecfc25b308da7659d9674e5fbc9638b1745f0e01d9/analysis/1490863773/

**Comment by isaacwhanson** [comment]
Definitely a false positive.

Thanks for this report, I will try to get swansetup added to their heuristics.

Programs that download an executable can get flagged this way sometimes.
