### ISSUE TITLE
spm -u today reset profile and removed shortcuts

### ISSUE THREAD

**Issue by SharkWipf** [starlight/swan-desktop#29]
I ran spm -u today, it installed the new fancy black theme, but also removed all start menu shortcuts for launching Swan (or at least, I can't find anything searching for "swan" or "xfce").
If I launch Swan using the shortcut I created in the autostart folder (`C:\lux-x86_64\bin\run.exe --quote /usr/bin/bash.exe -l -c "cd; exec /usr/bin/startx /etc/X11/xinit/Xsession xfce"`) it starts fine, but seems to use a new home folder with a new bashrc, vimrc, etc.  
My old home folder still is in the same place, I haven't found where exactly this new home folder lives.  

My install still uses `C:\lux-x86_64`, I suspect that might have had to do with it.  

Offtopic: Congrats on [making it to Hackaday](http://hackaday.com/2017/03/29/swan-better-linux-on-windows/) and consequently to my Google Now feed :)

**Comment by SharkWipf** [comment]
Whoops, just saw the post on the blog about the moved home folder.  
Might be good to find a way to somehow otherwise inform users of big changes like this?  

Shortcuts are still gone though so this bug report is still valid.

**Comment by isaacwhanson** [comment]
Well crap, `swan-desktop` should have recreated the shortcuts.  Try running `spm -u -M` (to bring up the Cygwin setup in package selection mode).  Make cygwin re-install the packages `swan-desktop` and `swan-base` and see if it recreates the shortcuts.  There should be a start menu folder called "Swan" with the shortcuts, and also shortcuts on the desktop.

good point about informing about major changes, getting too many users to just do things willy-nilly.

**Comment by isaacwhanson** [comment]
Oh jeez.  Didn't see the Hackaday article.  Wow, that explains the latest up-ticks.  :)

**Comment by SharkWipf** [comment]
Force-reinstalling swan-desktop and swan-base did the trick, shortcuts are back after that. Thanks!  
Not sure why it didn't re-add them automatically, maybe spm/cygwin setup crashed midway through?  
Happened to me before and Cygwin doesn't really let you know when it fails to install a package, it just closes without error.  
~~Lux~~ Swan is really starting to get traction now, I'm glad I'm not the only (confirmed) user anymore, haha. If the project grows so much that your server can't handle it anymore, my offer to provide a mirror for your site and/or the packages still stands :)

**Comment by isaacwhanson** [comment]
Arch Linux has the same problem with major changes, if you have any suggestions on how to better inform users, let me know.  A nag message in the package management system? I will give it thought.

**Comment by SharkWipf** [comment]
That's actually one of the main reasons I prefer Gentoo over Arch, haha.  
I'll open a new issue for this, easier to keep track of things.
