### ISSUE TITLE
Notify users of important changes

### ISSUE THREAD

**Issue by SharkWipf** [starlight/swan-desktop#31]
As mentioned in #29, it might be good to have some way to notify users of important changes.

Currently, this happens only through blog updates on [the project site](http://www.starlig.ht/), but users likely won't always read this.

Some thinking out loud:  
If we assume action will only be needed after updates and there's no need to warn users in advance, one could add a very simple changelog somewhere on the system. The problem then is getting users to read it.  
I can think of 3 options here:  

1. Have an icon on the default dock that opens the changelog in the default text editor.
This would give easy acces but wouldn't warn the user of new changes.
This also gives users the freedom to disable the icon if they want.
2. Use libnotify or the Windows notification system to display a message.
This message disappears after a few seconds though and can easily be missed.
3. Create a simple program that gets run by swan-desktop or swan-base on install, checks if there's new messages and if so, shows a tray icon in the dock that opens the changelog and closes the program if clicked.
This icon would be gone after a restart however (unless you add it to autostart with Swan).  
4. Inject "nag-messages" in the installer. Debian does this. Not sure how feasible this is with Cygwin though.  

Personally I'd like the changelog to be reachable from the dock, directly or through a menu, so users can access it at all times without having to search for it.  
Combining it with options 2 or 3 would allow users easy access to the changelog and would alert users of important changes.  
With option 3 it'd be important that the tray application only runs until the log is read and doesn't run non-stop. This way it'd be fairly non-intrusive and wouldn't waste any resources.

**Comment by isaacwhanson** [comment]
Excellent ideas here.  The project definitely needs a changelog, and a way to inform users of important changes.  This could also entail a more strict release system, now that the project is gaining some traction.  Documentation is also something to which users should have easy access.  Thanks for the list of good options.

**Comment by isaacwhanson** [comment]
Added a ChangeLog with notifier much as we discussed.  let me know what you think.

**Comment by SharkWipf** [comment]
Looking good! Seems to work with the latest update.  
Clever way of doing things, too.  
One issue I've noticed, but I guess a bug in XFCE4 and probably not something you can easily fix:  
If your notification area in the dock isn't on the outer edge, clicking the icon will make it disappear fine, but it'll also click the launcher that took its place. 
I.E.: 
![image](https://cloud.githubusercontent.com/assets/751205/24608157/a153fb70-1875-11e7-8361-eeede0d679c8.png)
Clicking it will launch SPM (or the default browser if you click on the far left).  
Not a big issue of course, probably not worth looking into and can easily be worked around by making sure the notification area is on the far left/right. just thought I'd mention it in case anyone else runs into it.

**Comment by isaacwhanson** [comment]
Yeah that may be hard to fix..
