### ISSUE TITLE
Capturing console output for Java processes

### ISSUE THREAD

**Issue by tuhlmann** [starlight/swan-desktop#32]
I use my computer mainly for Java stuff (Scala and Clojure), I usually start the build process from the terminal.

For Leiningen (Clojure, also Java based) that works fine, for sbt (Scala), I don't see any console output once the Java process is started, it seems to work though.

In it's simplest form the sbt shell is started as:

```
java -jar sbt-launch.jar
```
I see the process start up, I can enter a command, but nothing else is shown, like in this example:

```
$ java -jar target/sbt/bin/sbt-launch.jar 
[info] Loading project definition from C:\entw\aktuell\my-web\project
[info] Set current project to root (in build file:/C:/entw/aktuell/my-web/)
[info] F,o,u,n,d, ,p,r,o,x,i,e,s,:, ,{,},:, ,W,r,a,p,p,e,d,A,r,r,a,y,(,[,],)
[info] Node v4.2.6 is already installed.
[info] Found NPM version 2.14.16
> clean

```
I also tried a .bat wrapper script for sbt, but that didn't help either. I have no problems running the swan bash interpreter through ConEmu, but I way prefer the XFCE terminal :)

Is there something I can debug or do?

**Comment by isaacwhanson** [comment]
For `sbt`, the reference suggests creating a bash script for use with cygwin:

/usr/local/bin/sbt
    SBT_OPTS="-Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -
    XX:MaxPermSize=256M"
    stty -icanon min 1 -echo > /dev/null 2>&1
    java -Djline.terminal=jline.UnixTerminal -Dsbt.cygwin=true $SBT_OPTS -jar sbt-launch.jar "$@"
    stty icanon echo > /dev/null 2>&1

Does that work for you?
http://www.scala-sbt.org/0.13/docs/Manual-Installation.html

**Comment by tuhlmann** [comment]
Thank you for reading the manual I was supposed to read :)
It works wonderfully!
