### ISSUE TITLE
After installing, I don't see the swan Desktop shortcut anywhere 

### ISSUE THREAD

**Issue by userWayneCampbell** [starlight/swan-desktop#34]

**Comment by isaacwhanson** [comment]
Not on the desktop, not in the start menu (in Swan folder)? Anything that may be special about your setup?

**Comment by userWayneCampbell** [comment]
I installed it in the default directory, I don't see it in the start menu or the desktop. Is the actual file somewhere in the main directory?

**Comment by isaacwhanson** [comment]
No, the shortcut runs a command with arguments, not a simple link to a file. I will take a look tonight and see how we can troubleshoot. The missing shortcut is a sign it did not install

**Comment by isaacwhanson** [comment]
Does the file `C:\ProgramData\Swan\bin\xfce4-session` exist?

**Comment by userWayneCampbell** [comment]
Yes, I see that executable.

**Comment by isaacwhanson** [comment]
Could you try repeating the SwanSetup installer with the same target folder?

**Comment by userWayneCampbell** [comment]
Reinstalled and it works fine, Thanks.
