### ISSUE TITLE
cannot create directory ‘/cygdrive/c/Users/Macbook\nPro’

### ISSUE THREAD

**Issue by electronoob** [starlight/swan-desktop#35]
My logged in user has a space in the name, swan no like it. :(

http://i.imgur.com/N3Uo0vO.png

**Comment by electronoob** [comment]
no idea why it's converting the space to a new line character?

**Comment by SharkWipf** [comment]
User names with a space are known not to work well with Cygwin (see [Cygwin FAQ](https://www.cygwin.com/faq.html#faq.setup.name-with-space)).  
Sadly there's not much Swan can do about this.  
You can try changing the home path to something without a space (IIRC Swan runs as user `Swan` already so no need to change that), or changing your user name in Windows.  
It's annoying but at least it should work then.
