### ISSUE TITLE
Username with space migration to username without space

### ISSUE THREAD

**Issue by jackluo923** [starlight/swan-desktop#37]
What is the proper way of migrating from username with space to username without space? 

Currently I followed the 1st answer on stackoverflow: 
http://stackoverflow.com/questions/19613654/rename-change-cygwin-username
> mkpasswd -l >/etc/passwd 
then changed the username, group and changed home folder to another folder without space

Everything is well except that now my home folder location is in 
C:\Users\<username>\AppData\Roaming\Swan instead of C:\ProgramData\Swan\home\<home folder name without space>
How can I remap it to the proper location? I.e. I can create a symbolic and link the two folders, but I don't think that's the proper way to do it. 

Also in the Cygwin terminal under /home directory, '<username with space>' folder cannot be deleted even though it is deleted using Windows explorer. How can I solve this problem?

**Comment by isaacwhanson** [comment]
You would want to change your username using Windows, not anything in cygwin.

**Comment by SharkWipf** [comment]
Sadly, even that won't help I think. Renaming your Windows user account on recent Windows versions (8+ I believe) doesn't actually rename the folders IIRC, it just "simulates" a rename but keeps the same paths.  
@jackluo923 currently Swan is hard-coded to set its home in AppData/Roaming/Swan, if you want to change that you'd have to manually edit the file `/etc/profile.d/00-skel.sh` to target a new folder without spaces in it. 
In fact, if you mess up that file your home will be set to the install location automatically (but without links to your Windows folders), so changing it shouldn't be too difficult.  
That said, I haven't tried changing home like this and, while I believe it should work, YMMV.

**Comment by isaacwhanson** [comment]
Good points @SharkWipf .  Your user profile folder would still have the old name.  Changing that would require renaming the folder (as Administrator) and making the needed registry changes to have Windows pick up the change, instead of recreating the old folder.  I am afraid you are on your own with that one :)

**Comment by SharkWipf** [comment]
I've tried that once, renaming the folder and making the required registry tweaks. Ended up ruining my entire Windows installation and had to reinstall. I'd recommend against playing with that unless you're ready to deal with the consequences :)  
Changing the 00-skel.sh file to a path with no spaces (C:\Swan? D:\home?) should still work though, the only thing you should be able to break with that is Swan itself.

**Comment by jackluo923** [comment]
@SharkWipf  Thanks for reminding me that AppData/Roaming/Swan is actually the correct home folder. 

In the end, the migration is successful. Here are the following steps: 
> mkpasswd -l >/etc/passwd
Modify the line containing your space containing username in /etc/passwd from 
<space containing username>:*:197609:197609:<space containing group>,S-1-5-21-3667280834-385161257-1704048012-1001:/home/<space containing user name>:/bin/bash
to
<new username>:*:197609:197609:<space containing group>,S-1-5-21-3667280834-385161257-1704048012-1001:/home/<new username>:/bin/bash

After saving /etc/passwd file, close everything including xfce. To be safe, restart your computer. 

After coming back to the terminal, things will be a bit weird. You need to modify the ownership of all the files to your new username
> cd /home
> chown -R <new username>
Then close everything and/or restart your computer/cygwin

To verify that the changes are good, checking whether bash folder vs file name color highlighting is working. If it is, then it means .vimrc file in the home directory is working. If it is, then Cygwin should have your new username properly mapped to your new home folder. By default, bash should also display <username>@<machineName>. If that is what you expected then everything should be good. 

The problem I mentioned that I cannot remove '/home/<username with space>' problem is resolved removing it using Windows and restarting the machine.
