### ISSUE TITLE
Python-pip doesn't install with SPM

### ISSUE THREAD

**Issue by ivdok** [starlight/swan-desktop#38]
`$ spm -s python`
`python`
`python-pip`
`<...>`
`$ spm -i python python-pip`
`<...>`
`$ pip`
`-bash: pip: command not found`

Where did it go wrong? It just skips through the actual download/install phase straight to pre/post-install routines without spitting an error.

**Comment by SharkWipf** [comment]
Hmm. spm -S tells me python-pip is deprecated and if you try to install it it should install python2-pip.  
I tried installing python-pip and it did exactly as promised, pulled in python2, pulled in python2-pip.  
It seems to work fine for me, keep in mind it installs as pip2 and pip2.7, you don't get the pip command. Do you not have these commands either?

**Comment by isaacwhanson** [comment]
`spm -s` or `spm --status` shows packages that are already installed.  The setup is skipping the download/install phase because it is already installed.

**Comment by ivdok** [comment]
If I remember it correctly, I've bruteforced the issue by installing whole
Python group from Cygwin installer, otherwise it wouldn't work.
easy_install missing, downloading "that one installer" didn't do anything
either. Hell, even python3 executable has gone rogue at some point and
decided to nope out of existence. Usually Linux distros use environment
variables to switch Python versions, but Cygwin decided instead to mess
with packages. It took me a good hour to fix it and launch the script I
wanted.
