### ISSUE TITLE
Failed downloading setup-x86_64.exe

### ISSUE THREAD

**Issue by aceverett** [starlight/swan-desktop#39]
Hello. I just discovered your project and I was ready to give it a go. Anyway, SwanSetup fails quite early in the install process. Here's the error I get:

```
Create folder: C:\ProgramData\Swan\var\cache\spm
download failed: C:\ProgramData\Swan\var\cache\spm\setup-x86_64.exe
```

**Comment by isaacwhanson** [comment]
Interesting.  Does the folder `C:\ProgramData\Swan\var\cache\spm` get created?
Are you able to access the url `https://cygwin.com/setup-x86_64.exe`?  It is possible that you have an antivirus that is incorrectly blocking the download.

**Comment by schade** [comment]
I too have hit this bug and can verify that the `C:\ProgramData\Swan\var\cache\spm` directory does get created.

**Comment by MJBrune** [comment]
Same issue and I can confirm I both had that directory created and can reach that path and additionally I went a step further and placed the exe in that path and it still stupidly tried to download it, failed and had the exact same error as before.

**Comment by isaacwhanson** [comment]
What antivirus do you have?  Is it being blocked or quarantined?

**Comment by MJBrune** [comment]
Windows 10 comes with Defender. That's what I have installed.

**Comment by schade** [comment]
Panda Antivirus on Windows 10 and no quarantine or even reference to the
Swan installer can be found.

Jerry W Jackson
a Committee of Lunatics, LLC

**Comment by isaacwhanson** [comment]
Crap, sorry you guys are having issues.  Been trying to reproduce the issue here, and SwanSetup is working just fine for me.  Going to keep trying here, and will keep you updated.

**Comment by schade** [comment]
What version of Windows 10 is everyone using? Is it a release? or an Insider build? This might be relevant to @isaacwhanson being able to test. I am on Windows 10 Pro - Insider build 16184.

**Comment by SharkWipf** [comment]
Same, I've tried installing it on a machine that's never run Swan before and it installs just fine.  
@schade you just ninja'd me, I was just going to ask what versions of Windows everyone is using.  
In my case I got it running fine on a Win10 Pro and a Win10 Pro N, both 64-bit (does 10 even support 32-bit still?), both running only Windows Defender.  
Any other information you're able to provide about your systems is welcome as I'm not sure what could be causing this either.

**Comment by schade** [comment]
@SharkWipf It was the logical next item. Windows 10 does not come in a 32 bit flavor but supports 32-bit applications if installed correctly. I will test without Panda and see if it might be the (silent) culprit here and get back with my results.

**Comment by MJBrune** [comment]
Tried running the setup today and it worked. No clue why it wasn't working
yesterday. Might be an Open Office can't print on Tuesday sort of thing?

**Comment by SharkWipf** [comment]
Hmm, odd. Maybe there just was an outage at Cygwin?  
I did notice the installation took a lot longer than I remembered, particularly downloading the Cygwin packages, so maybe Cygwin is just having issues.  
Does it work for you too now, @schade and @aceverett?

**Comment by schade** [comment]
@SharkWipf It was the logical next item. Windows 10 does not come in a 32 bit flavor but supports 32-bit applications if installed correctly. I will test without Panda and see if it might be the (silent) culprit here and get back with my results.

**Comment by schade** [comment]
It does work for me now. I had already uninstalled the Antivirus but hadn't rebooted yet so Cygwin themselves must have been the cause. Maybe we should better word the error?

**Comment by MJBrune** [comment]
I don't think it was cygwin because I was able to download that file
directly yesterday.

**Comment by arizonneto** [comment]
Same issues here, fresh windows 10 education with defender (tried disabling). Installing cygwin from the source works fine.

Win version is 1607.

**Comment by isaacwhanson** [comment]
There was reported in the cygwin mailing list a couple days ago some issues with downloading the setup file, maybe a temporary issue with the hosting?

**Comment by MJBrune** [comment]
could be a load balancing issue on their end? One of their servers has the
correct exe and they made a game of downloading it. You gotta refresh until
you get the right one.

**Comment by SharkWipf** [comment]
Yeah, that's what I expect. Either that or just a flakey server in general,
both could explain the weird behaviour with manual downloads (sometimes?)
working where installer downloads fail.
A better error message might be good, although I'm not sure how one would
word it. The installer can't detect the difference between a Cygwin problem
and a firewall problem, so best one could do is improve the "download
failed" message.

**Comment by isaacwhanson** [comment]
A new version of [SwanSetup.exe](http://sirius.starlig.ht/SwanSetup.exe) has been released that will produce a small amount of info regarding the reason for the failed download (for example `File not found (404)`).  Perhaps it will help those who may still be having issues.

**Comment by MJBrune** [comment]
Windows Defender doesn't like that exe btw. Deletes it immediately. So when
you download it disable defender I guess.

**Comment by SharkWipf** [comment]
Hmm, what one? the Cygwin setup-x86_64.exe or the SwanSetup.exe? 
I've redownloaded and scanned both with Windows Defender and both came out clean for me.

**Comment by MJBrune** [comment]
This is what I get with the newest SwanSetup Exe with the newest
definitions of windows defender with windows 10.

The following error occurred: Error code 0x80508023. The program could not
find the malware and other potentially unwanted software on this computer.

Category: Trojan

Description: This program is dangerous and executes commands from an
attacker.

Recommended action: Remove this software immediately.

Items:
file:C:\Users\admin\Downloads\SwanSetup (1).exe
webfile:C:\Users\admin\Downloads\SwanSetup (1).exe|
http://sirius.starlig.ht/SwanSetup.exe|chrome.exe

Get more information about this item online.

**Comment by isaacwhanson** [comment]
Ok. yet another version uploaded, refactored slightly as not to trigger Windows Defender.  You may need to clear your cache to download the latest.

**Comment by SharkWipf** [comment]
@MJBrune if it still gets flagged for you, could you check the SHA-sum of the file?  

@isaacwhanson semi-related: Might be worth looking into setting up SSL on Sirius, that'd at least rule out in-flight tampering with the file as it's being downloaded. Fairly easy (and free) to set up with LetsEncrypt as well.

**Comment by isaacwhanson** [comment]
@SharkWipf good idea.  I have been able to reproduce the defender issue locally, so I can rule out a MITM attack for this particular issue.

**Comment by MJBrune** [comment]
@Sebastiaan: Still triggers:

 [image: Inline image 1]

**Comment by isaacwhanson** [comment]
Ok, I submitted to Microsoft for whitelisting.  I will see what I can do in the meantime.

**Comment by MJBrune** [comment]
Cool, I was able to just set it up yesterday and so defender shouldn't
effect me. I know it's better to submit for whitelisting than just have
your exe deleted automatically. :)

**Comment by isaacwhanson** [comment]
Microsoft seems to accept my whitelisting requests, which I suppose I will have to make every time I make a new version of the installer.
