### ISSUE TITLE
Xfce4 panel doesn't show any icons and launching "Appearance" from "Swan->Settings" causes dump 

### ISSUE THREAD

**Issue by Bob3001** [starlight/swan-desktop#40]
Everything was working fine until the last Win10 update. It killed my icons I had pinned to the taskbar and then SWAN came up with this issue. At first I could launch the appearance settings but after trying to select a different icon them it crashed on me and won't start. Everything else seems to work though just no icons and I'm not able to change the theme. I've tried reinstalling all the GUI related packages but that won't solve the issue. Even tried using gtk-update-icon-cache without success though.

The output of the dump:
$ cat xfce4-appearance-settings.exe.stackdump
<snipped>

**Comment by Bob3001** [comment]
More to come, using CTRL+SHIFT+T to add a tab will crash Mate and Gnome terminal window:

$ cat mate-terminal.exe.stackdump
Stack trace:
Frame        Function    Args
000FFFF8870  0018005CC8C (000FFFFE3F4, 006007CCFA0, 001800B9EB2, 000FFFFDE50)
000FFFF8910  0018005E25B (00000000064, 00000000000, 00000000000, 00000000000)
000FFFF8B60  0018011E1A3 (00000000003, 00000000000, 00000000000, 0018013C831)
000FFFF8E50  0018011AE5E (00000000400, 00000000000, 00000000000, 00180140EF0)
003E632ADB0  0018011B2E9 (000000000AE, 000000000AE, 00180116AFB, 00000000006)
003E632ADB0  0018011B49A (000FFFF8FA0, 003E632ADB0, 003E632AB88, 006000D8D80)
003E632ADB0  0018011B74F (000FFFF8FA0, 006007C6E07, 515143FF00000000, 00000000000)
003E632ADB0  003E7F84125 (003E632AC28, 003E7FB7CB2, 00000000000, 006007CCF70)
000000001ED  003E7F841A2 (000FFFF9010, 00000000000, 00180142668, 003E632AC28)
00000000001  003E60FF6AB (00000000039, 0060066F990, 00000000000, 00600720C70)
00000000001  003E60FFD59 (003E7F440BD, 006007C88A8, 00000000001, 006007C88B0)
0060054F1E0  003E60FFEA4 (003E7819DFF, 000FFFF95B4, 003E78376F3, 000FFFFFFFF)
0060054F1E0  003E6100078 (003E608B922, 006000EF7D0, 003E8816B5E, 006000FC350)
0060054F1E0  003E611359A (00000000000, 00000000000, 00000000000, 000FFFF95B4)
0060054F1E0  003E607989B (00000000000, 00000000000, 00000000000, 000FFFF95B4)
0060054F1E0  003E607DC3F (00300000000, 0018013C831, 0018013E3DF, 000FFFF95B4)
End of stack trace (more stack frames may be present)


$ cat gnome-terminal-server.exe.stackdump
Stack trace:
Frame        Function    Args
000FFFF8D00  0018005CC8C (000FFFFE3F4, 0060081D230, 001800B9EB2, 000FFFFDE50)
000FFFF8DA0  0018005E25B (00000000064, 00000000000, 00000000000, 00000000000)
000FFFF8FF0  0018011E1A3 (00000000003, 00000000000, 00000000000, 0018013C831)
000FFFF92E0  0018011AE5E (00000000400, 00000000000, 00000000000, 00180140EF0)
003E632ADB0  0018011B2E9 (000000000AE, 000000000AE, 00180116AFB, 00000000006)
003E632ADB0  0018011B49A (000FFFF9430, 003E632ADB0, 003E632AB88, 006000D3F30)
003E632ADB0  0018011B74F (000FFFF9430, 0060081CD57, 515143FF00000000, 00000000000)
003E632ADB0  003E7F84125 (003E632AC28, 003E7FB7CB2, 00000000000, 0060081D200)
000000001ED  003E7F841A2 (00180142668, 00000000000, 00180116AFB, 003E632AC28)
00000000001  003E60FF6AB (00000000039, 00000000000, 00000000000, 00600494630)
00600494630  003E60FFDB9 (003E7F440BD, 006007A5C48, 00000000001, 006007A5C50)
006005132E0  003E60FFEA4 (003E7819DFF, 000FFFF9A44, 003E78376F3, 000FFFFFFFF)
006005132E0  003E6100078 (003E608B922, 006000EB980, 003E8816B5E, 006000FB350)
006005132E0  003E611359A (00000000000, 00000000000, 00000000000, 000FFFF9A44)
006005132E0  003E607989B (00000000000, 00000000000, 00000000000, 000FFFF9A44)
006005132E0  003E607DC3F (00300000000, 0018013C831, 0018013E3DF, 000FFFF9A44)
End of stack trace (more stack frames may be present)

$ cat exo-helper-1.exe.stackdump
Stack trace:
Frame        Function    Args
000FFFF7D00  0018005CC8C (000FFFFE3F4, 006001BD9E0, 001800B9EB2, 000FFFFDE50)
000FFFF7DA0  0018005E25B (00000000064, 00000000000, 00000000000, 00000000000)
000FFFF7FF0  0018011E1A3 (00000000003, 00000000000, 00000000000, 0018013C831)
000FFFF82E0  0018011AE5E (00000000400, 00000000000, 00000000000, 00180140EF0)
003E632ADB0  0018011B2E9 (000000000AE, 000000000AE, 00180116AFB, 00000000006)
003E632ADB0  0018011B49A (000FFFF8430, 003E632ADB0, 003E632AB88, 006000B7880)
003E632ADB0  0018011B74F (000FFFF8430, 006001BD9D7, 515143FF00000000, 00000000000)
003E632ADB0  003E7F84125 (003E632AC28, 003E7FB7CB2, 00000000000, 0060031F6C0)
000000001ED  003E7F841A2 (000FFFF84A0, 00000000000, 00180142668, 003E632AC28)
00000000001  003E60FF6AB (003E6289D88, 0060025B000, 00000000000, 006002764D0)
00000000001  003E60FFD59 (012FFFF8A44, 006000B1550, 003E7818477, 000FFFF8A44)
006003B3360  003E60FFEA4 (0060038B420, 006000E7700, 00000000000, 00000000000)
006003B3360  003E6100078 (000FFFF8A48, 00600010830, 003E7819DFF, 00000000000)
006003B3360  003E611359A (00000000000, 000FFFF8850, 00000000000, 000FFFF8A44)
006003B3360  003E607989B (006001ADA10, 00000000004, 0000000002F, 000FFFF8A44)
006003B3360  003E607DC3F (00300000001, 0060038B590, 003E61D997B, 000FFFF8A44)
End of stack trace (more stack frames may be present)

**Comment by isaacwhanson** [comment]
I will look into this.  no need to post the stack dumps.

**Comment by isaacwhanson** [comment]
I updated Windows 10 today, installed `gnome-terminal`, `mate-terminal`, and I am having no issues with either.  Also no issues with Xfce settings.

So some questions, and something to check...

1.  Have you rebooted and are still seeing the issues?
2.  Have you updated Swan (using "Software Update" icon, or `spm -u`)
3.  Try running `cygcheck -c` to verify the integrity of installed packages.
4.  Could you check your anti-virus and Windows defender "quarantines" for false-positives?

**Comment by Bob3001** [comment]
Seems OK since yesterday after an update. Only thing not working is the intelligent hiding of the panel but I can live with that. All seems good now thanks for the effort!

1. rebooted several times issue gone with package update
2. yes and now it's working
3. done all OK
4. as it's a VDI install the virus check is performed on another level that I don't have access to

**Comment by isaacwhanson** [comment]
yeah intelligent hiding will probably never work. glad you are sorted.
