### ISSUE TITLE
sirius.starlig.ht is down

### ISSUE THREAD

**Issue by rajelaran** [starlight/swan-desktop#42]
The SwanSetup.exe installer cannot be downloaded due to timeouts on sirius.starlig.ht
Same goes for the magic install command from https://github.com/starlight/swan-desktop/issues/26 - sirius.starlig.ht-hosted files fail to download.

This has been confirmed from multiple geo-diverse peers in the US.

**Comment by SharkWipf** [comment]
Can confirm, updating existing Swan installations times out for me on Sirius as well.

**Comment by isaacwhanson** [comment]
shoot.  bringing it back from backups.  should be back within seconds.

**Comment by isaacwhanson** [comment]
Sorry I didn't see this sooner.
