### ISSUE TITLE
[SOLVED] Chinese word display ok, but input is unusable

### ISSUE THREAD

**Issue by zzyongx** [starlight/swan-desktop#43]
I am a user from china. My swan-desktop can display chinese word, but input is unusable.
On the below screenshot，create a chinese file name is impossible。
Is it a config problem or swan-desktop function problem？How could i fix it？
![qq 20170801182913](https://user-images.githubusercontent.com/4651163/28821277-6e7bb51e-76e7-11e7-9dd5-25749a98a979.png)

**Comment by isaacwhanson** [comment]
I believe your input method needs to be changed to use ibus. I will try to find a solution for you.

**Comment by zzyongx** [comment]
I install ibus and ibus-pinyin, config ibus. But the input method switch is not work. I only got space when i pressed alt+space. Is it conflict with windows system?
![image](https://user-images.githubusercontent.com/4651163/28857600-49e43154-777d-11e7-9124-81d5b0b9028a.png)

**Comment by isaacwhanson** [comment]
it looks like you have it set to Ctrl-space, not alt. I would try to use a different key if it does not work. I will try to make a solution in about 8 hours from now.

**Comment by isaacwhanson** [comment]
Ok, I was able to get ibus-pinyin to work.  Warning, I cannot read hanzi so I have no idea what these screenshots actually say. :)

1. Start by logging-out of Xfce.
2. Open the Swan Console and install ibus-pinyin:  `spm -i ibus-pinyin`
3. Start Swan Xfce4 Desktop.  Open IBus Preferences. (it will start ibus, it complained about an error but worked fine for me anyway).
4. Under "next input method" delete any existing keyboard shortcut.
5.  Add the new shortcut with the checkboxes for Alt or Control and space for the keycode and hit "Add".
![image](https://user-images.githubusercontent.com/907767/28898695-5c2acae8-77b5-11e7-9408-501771f692f0.png)

6.  Add the pinyin input method on the "Input Method" tab of IBus Preferences.
![image](https://user-images.githubusercontent.com/907767/28898688-496a9636-77b5-11e7-9359-2b64ecf611e0.png)

7.  Save all your settings and close the preferences.

I am now able to use pinyin input using either Alt or Control + Space.
![image](https://user-images.githubusercontent.com/907767/28898705-6c12819e-77b5-11e7-9aea-4fa2a60dc48b.png)

**Comment by isaacwhanson** [comment]
You may also want ibus-daemon to run on startup.  You can add it to your startup in "Session and Startup" >> "Application autostart"

**Comment by zzyongx** [comment]
Thank you very much. It works for me too. I add those lines in bash_profile as ibus preferences's suggestion.  Input chinese work in Terminal may need it. It's a great desktop, I will recommend it to my colleagues and friends.

`export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus`

**Comment by isaacwhanson** [comment]
I ended-up adding ibus support to swan-desktop, including an autostart script for the daemon.
