### ISSUE TITLE
Cannot install swan-desktop on newest Windows

### ISSUE THREAD

**Issue by jackluo923** [starlight/swan-desktop#44]
After going through the "usual" install process on a fresh and updated windows: 
1) click next, next, next..etc
2) Cygwin showing it is downloading a bunch of packages

swan-desktop doesn't seem to be installed properly. 

Behavior: 
C:\ProgramData\Swan only contains the following folders and file: 
-etc
-var
-unins000.dat
-unins000.exe

No icons or installation file seems to be created. 

After taking a look at the log, it seems to be that Cygwin mirror is partially down.  How to fix this problem?
```
2017/08/15 22:38:17 download error in unattended_mode: 0 retry remaining.
2017/08/15 22:38:17 site: http://cygwin.mirror.constant.com/
2017/08/15 22:38:17 site: http://sirius.starlig.ht/
2017/08/15 22:38:19 HTTP status 404 fetching http://cygwin.mirror.constant.com/x86_64/release/openjpeg/libopenjpeg1/libopenjpeg1-1.5.2-3.tar.xz
(snipped)
2017/08/15 22:38:19 HTTP status 404 fetching http://cygwin.mirror.constant.com/x86_64/release/poppler/libpoppler-glib8/libpoppler-glib8-0.52.0-1.tar.xz
(snipped)
http://cygwin.mirror.constant.com/x86_64/release/poppler/libpoppler66/libpoppler66-0.52.0-1.tar.xz
2017/08/15 22:38:19 download error in unattended_mode: out of retries
2017/08/15 22:38:19 note: Installation incomplete.  Check C:\ProgramData\Swan\var\log\setup.log.full for details
2017/08/15 22:38:19 Ending cygwin install
```

**Comment by isaacwhanson** [comment]
That is a mirror not in my control. Hopefully, it will be back up soon. Or if you need to use an alternate Cygwin mirror, you can change the one used with the `spm -c` command.

**Comment by jackluo923** [comment]
It seems like many (updated) mirrors have empty directories:
http://cygwin.mirror.constant.com/x86_64/release/poppler/
http://cygwin.mirror.rafal.ca/x86_64/release/poppler/
http://mirrors.metapeer.com/cygwin/x86_64/release/poppler/

however, "outdated" mirror like this one has it. 
http://mirror.esc7.net/cygwin/x86/release/poppler/libpoppler66/

Do you know if this is a general issue?

**Comment by isaacwhanson** [comment]
You seem to be correct. Looks like a bug that was synced across the mirrors. I will try to file a report today.

**Comment by isaacwhanson** [comment]
Sent a report to Cygwin, hopefully the packages will be back soon.

**Comment by isaacwhanson** [comment]
looks like sourceware.org had a big fail due to a hardware upgrade, and are restoring from backups.  may be some quirks with the mirrors while they fix it.

**Comment by isaacwhanson** [comment]
explanation of issues at sourceware.org:
https://www.sourceware.org/ml/overseers/2017-q3/msg00060.html

**Comment by isaacwhanson** [comment]
it should be back up.  let me know if you see any other missing packages.

https://cygwin.com/ml/cygwin/2017-08/msg00154.html

**Comment by jackluo923** [comment]
I can confirm this is no longer a bug. :)

**Comment by isaacwhanson** [comment]
Thank you!  The guys at Cygwin didn't know those were missing, and your detailed report with log file was very helpful.
