### ISSUE TITLE
xfce4-panel sometimes closes when dragging

### ISSUE THREAD

**Issue by SharkWipf** [starlight/swan-desktop#45]
Haven't had time to really debug this yet, but on my laptop xfce4-panel randomly closes when I'm trying to drag it. It's difficult to properly debug it because it doesn't always happen.  
Other applications continue running fine when the panel crashes. I plan to debug it better soon.  

This happens on my laptop, so W10 Pro with the latest creators update.  
It might be related to display scaling as one monitor is configured at 150% zoom and the other at 100%. I'm constantly dragging the panel between them and it does behave wonky when doing so every now and then.

**Comment by SharkWipf** [comment]
After some more testing it doesn't actually close, it just jumps off-screen.  
I'm guessing this has to do with the display scaling as I don't have this issue on non-scaled setups, it also behaves strangely when moved between scaled and unscaled displays.  

@isaacwhanson I don't think this is something that can be fixed in Swan, do you? I'd guess this is a Cygwin issue, not something that can be fixed by changing X11 settings.

**Comment by isaacwhanson** [comment]
it may be related to the `-multimonitors` flag passed to XWin.  It creates one screen that covers multiple monitors using faked xinerama data.  maybe remove that and try using the `-screen` option to describe each monitor separately.  never used it before, that is just a best guess.  I don't have a setup to test a solution, unfortunately.

**Comment by SharkWipf** [comment]
I plan on trying this but I won't have the time to test it anytime soon, pretty busy atm. I'll close it for now, if I find out later that it can be fixed this way I'll post back on this issue.
