### ISSUE TITLE
Performance issues.

### ISSUE THREAD

**Issue by jordwalke** [starlight/swan-desktop#46]
Hello,

This is a fantastic project. I can tell you've put a lot of work into ensuring the install/setup and out-of-box experience is really polished.

I have noticed that windows (including text terminals) run very slow.
For example, if I install standard cygwin and do a simple `ls` command in a directory it's quite fast. If I run the Swan xfce terminal program and do a simple `ls` command it is much slower.

Any idea what's going on here? Is it the X server getting in the way?
(The Swan Console is as fast as default Cygwin installation MINTTY).

If the windowing performance was improved to become close to the native windows drawing performance, I would probably use Swan to run the majority of my GUI applications on Windows.

**Comment by isaacwhanson** [comment]
How slow are we talking, here?  The slow-down should be small, less than half of a second on a reasonable machine.

**Comment by jordwalke** [comment]
The startup time for Swan took a second or so - that's fine. The time I'm mainly talking about is interaction time. A simple `ls` command in the cygwin MINTTY terminal was instant. The time in the Swan GUI terminal to do the same `ls` command seemed like about 300ms which was noticeably laggy.

**Comment by isaacwhanson** [comment]
Understood.  I will look into it and see if it can be improved.  Thanks for the report

**Comment by SharkWipf** [comment]
@jordwalke Do you have a `$PROMPT_COMMAND` set in your `~/.bashrc`?  
I have this issue in both Swan and "vanilla" Cygwin because of my `$PROMPT_COMMAND`.  
Due to the way Cygwin spawns processes, there's a small delay every time a new command is run, whereas native Linux doesn't have this issue.  
I can reproduce this even under Cygwin Terminal, which doesn't use the X11 server at all, and even if I run bash in cmd.exe.  
If I run `unset PROMPT_COMMAND` the problem disappears for me entirely however.

**Comment by SharkWipf** [comment]
Actually I just noticed I partially misunderstood your issue, I just noticed you were talking about individual commands like `ls`, and you've already tested Swan console too.  
Hmm okay, then I'm not sure, for me Swan Console and XFCE4 Terminal are pretty much equal for me in response times and I'm running Swan on a NUC. What kind of hardware do you run Swan on?

**Comment by jordwalke** [comment]
Core i7 1.3ghz. Mintty is fast.

**Comment by isaacwhanson** [comment]
I get the exact same time in both terminals, an average of 0.17 seconds to do `ls` (after 1000 iterations each).  You might check that you don't have "bloda" software interfering with Cygwin:

https://cygwin.com/faq/faq.html#faq.using.bloda

**Comment by isaacwhanson** [comment]
did anything on the bloda list ring a bell?

**Comment by jordwalke** [comment]
No. How is the bloda list relevant in this case?

**Comment by isaacwhanson** [comment]
It isn't if you don't have any of it installed.  Just trying to eliminate sources of poor performance.

**Comment by jordwalke** [comment]
I thought bloda was related to runtime failures, not performance issues. Do I have an incorrect understanding?

While I have you here, isn't there some automated way to remove all the bloda issues after performing a build of a set of packages? What if someone was to just automatically rebase everything after building everything. Wouldn't that solve all of the bloda issues (though it might be slow?)

**Comment by isaacwhanson** [comment]
I have seen performance issues arise due to some of this software.  Unfortunately, rebasing will not solve many issues (like hooks into the kernel subsystems).

**Comment by isaacwhanson** [comment]
I wonder if you XWin log file shows any issues with your rendering pipeline?

**Comment by jordwalke** [comment]
I can try next time I get Swan setup.
About my random question: Have you figured out a way to automatically solve the rebase issue in Swan without people having to run rebase sometimes on their own? Is it possible for Swan's package manager to simply always rebase everything after every install/uninstall?

**Comment by isaacwhanson** [comment]
It does auto-rebase on every install/uninstall currently.

**Comment by jordwalke** [comment]
Thanks for the info!
