### ISSUE TITLE
Terminator CTRL + Shift + E is hijacked by an emoji dialog

### ISSUE THREAD

**Issue by iongion** [starlight/swan-desktop#47]
In terminator, when splitting vertically, an emoji dialog appears:

![image](https://user-images.githubusercontent.com/867609/31876850-7699cfc8-b7d4-11e7-8090-d375bf3212cf.png)

Tried to remove it from binding, but it is not present.

**Comment by isaacwhanson** [comment]
Run ibus-setup and you can change/remove the binding.

**Comment by iongion** [comment]
Yes, that did the job! Thank you!
