### ISSUE TITLE
Can't update nor installing package

### ISSUE THREAD

**Issue by The-Butler** [starlight/swan-desktop#48]
Here is the error message I have when I try either spm -U or spm -i "package name"

Unable to start 'C:\Users\the.butler\AppData\Roaming\Swan\.cache\spm\setup-x86_64.exe': The operating system denied access to the specified file.

Any idea where does it come from and how to solve it ? I already try to change permission (chmod 755) nothing changed.

Thanks

**Comment by isaacwhanson** [comment]
Perhaps an issue with antivirus? Sometimes false positives occur.

**Comment by The-Butler** [comment]
Actually the only Antivirus I have is Windows defender but I'll check for that.
Thank you.

**Comment by isaacwhanson** [comment]
still having issues @The-Butler ?

**Comment by Iito** [comment]
Well I have try to change the owner of my C drive to administrator, after that I couldn't use my PC anymore so I re-installed windows.
Since Swan is working but I experience issue with windows haha (no more apps like mail or calendar)

Thank you

**Comment by The-Butler** [comment]
Well I have try to change the owner of my C drive to administrator, after that I couldn't use my PC anymore so I re-installed windows.
Since Swan is working but I experience issue with windows haha (no more apps like mail or calendar)

Thank you

**Comment by Iito** [comment]
Hello,

I experience the same issue, I didn't used Swan for a while and I think the issue came after updated it.
I also updated windows 10 as well so it might come from it.

**Comment by isaacwhanson** [comment]
You could try reinstalling.  If you *uninstall* Swan, none of the files in your personal home folder will be lost (backup anything else) and will be in the same spot on reinstall.

**Comment by Iito** [comment]
Okay, I did it but still same issue, something to do with permission needed.
That's really strange, I don't know why i just appears when it worked perfectly before.

**Comment by isaacwhanson** [comment]
The Swan installer should not require privileges/permissions beyond the normal user.  Is there anything interesting in the /var/log/setup.log ?

**Comment by Iito** [comment]
There is nothing interesant in the logs. If you want the file I can send it.

**Comment by isaacwhanson** [comment]
Sure  I will take a look at it next chance I get.

**Comment by The-Butler** [comment]
I'm experiencing the same issue as before, same as Iito.
One day it was working the day after when I try to do "spm -u" it's no longer working.
I don't know why, maybe windows update that change swan permission access.

**Comment by The-Butler** [comment]
Here is the folder's permissions 
![swan_issue](https://user-images.githubusercontent.com/33642875/34287731-7bd73b7e-e72c-11e7-905b-8c288a4f599e.jpg)

Does it sound correct to you ?

**Comment by isaacwhanson** [comment]
permissions look ok.  I notice that when you created the issue your username was `the.butler` but now it is `the-butler`.  I am not sure about the characters `.` or `-` in your name causing an issue?

**Comment by The-Butler** [comment]
Good for the permissions, is there any log I can check or share to help figure this out ?

The name "The-Butler" is not my computer name, I changed it to keep privacy. In my computer name it's "the.butler" type.

**Comment by isaacwhanson** [comment]
maybe check the permissions on the setup.exe?  does it have the executable bit set?  maybe you have a umask that is too restrictive?

**Comment by SharkWipf** [comment]
Sounds to me like a group policy, is this a work machine on a managed domain?  
Sounds like your network admin has added a rule that prevents Swan from running. If this is the case you should discuss it with your network admin, as working around their policies might actually be violating your workspace rules.  
Alternatively, I recall Cygwin having issues with user names with certain chars (and renaming your user account does *not* fix this), I don't recall if dots caused issues or not.
