### ISSUE TITLE
“Swan Xfce4 Desktop” shortcut not found

### ISSUE THREAD

**Issue by zielot** [starlight/swan-desktop#49]
Hi folks,

Second attempt to install this on a Windows 7 Professional machine running in a corporate network in the last 6 months. Both attempts ended the same - no shortcuts installed and it seems that Cygwin was not installed correctly:

/c/ProgramData/Swan/bin $
$ ./startxfce4
./startxfce4: Starting X server
./startxfce4: line 118: exec: xinit: not found

/c/ProgramData/Swan/bin $
$ ./exo-start
./exo-start: line 4: cygstart: command not found

/c/ProgramData/Swan/bin $
$ ./xfrun4
C:/ProgramData/Swan/bin/xfce4-appfinder.exe: error while loading shared librarie
s: cyggtk-x11-2.0-0.dll: cannot open shared object file: No such file or directo
ry

/c/ProgramData/Swan/bin $
$ ./xfce4-se
xfce4-session.exe           xfce4-settings-editor.exe
xfce4-session-logout.exe    xfce4-settings-manager.exe
xfce4-session-settings.exe

/c/ProgramData/Swan/bin $
$ ./xfce4-session.exe
C:/ProgramData/Swan/bin/xfce4-session.exe: error while loading shared libraries:
 cygX11-6.dll: cannot open shared object file: No such file or directory

Any help would be appreciated.

~ Justin

**Comment by SharkWipf** [comment]
First guess would be essential files get blocked by a virus scanner or group policy.  
Have you checked your virus scanner logs, if any?  
Does the installer log show any errors?

**Comment by isaacwhanson** [comment]
any update on this @zielot ?

**Comment by zielot** [comment]
Hi folks,

Sorry - wasn't able to get back to this until recently; thanks for the quick response to my original question.

I tried to reinstall a couple of days ago and I have the same problem.

- I have admin access on my corporate Windows 7 Professional Laptop and I have installed MSYS, VirtualBox, tomcat among many other programs. This doesn't look like it was blocked by group policy. Even so, I ran the Swan Setup executable as Admin just to verify that this wasn't the issue.
- I have not seen any popups indicating that McAfee had blocked or trapped an installed file. I  viewed the status panes and did not seen anything indicating that and install step was dropped. Having said that, I do not have the privileges to stop the antivirus agent.
- Where are the log files kept? I grepped through files in c:\Windows\temp, c:\temp, c:\users\{username}\AppData\Local\Temp for 'swan' and searched the Download folder to where I had downloaded the Swan setup file but did not see any logs.
- Which file am I supposed to run to start the xfce4? Do I need the desktop link?

Thanks.

Justin

**Comment by isaacwhanson** [comment]
- I would not advise installing as Admin in general.  Not that it will cause issues, just headaches with permissions.
- Ok
- The installer should be dropping log files here: `C:\ProgramData\Swan\var\log\`
- the command the shortcut runs: `C:\ProgramData\Swan\bin\run.exe /usr/bin/bash.exe -l -c "cd; exec /usr/bin/startx /etc/X11/xinit/Xsession xfce"`

**Comment by zielot** [comment]
I am sorry to be frustrating you folks with my slow response rate but I just wanted to let you know that finally - success! Today I deleted c:\programdata\swan, downloaded the new installer from http://www.starlig.ht/install/, ran the application as a regular user watched the logs from my MSYS  mintty console and everything works! Thanks for the help and the work creating this nice installer.

**Comment by isaacwhanson** [comment]
Excellent, glad to hear it!  Let us know what you think about it
