### ISSUE TITLE
Too many arguments

### ISSUE THREAD

**Issue by hafedh-trimeche** [starlight/swan-desktop#50]
Please note that an exception is raised when running :
$ spm -u
/usr/bin/spm: line 313: cd: too many arguments

-----------------------------------------
Windows 10 x64

**Comment by isaacwhanson** [comment]
please note the contents of /var/log/setup.log

**Comment by hafedh-trimeche** [comment]
This is the related Log.
[setup.log](https://github.com/starlight/swan-desktop/files/1625373/setup.log)

**Comment by isaacwhanson** [comment]
Cygwin does not like spaces in paths, unfortunately.  Try installing to the default location, or to a path without spaces.

**Comment by hafedh-trimeche** [comment]
Cygwin is already installed and works well.

 "D:\Swan" is the target directory for swan-desktop installation containing no space.

**Comment by isaacwhanson** [comment]
Ok great!  Glad it is working for you.  Let us know what you think

**Comment by hafedh-trimeche** [comment]
Sorry, I mean even Cygwin installed and "D:\Swan" is a regular directory, I can't get swan-desktop working.

**Comment by isaacwhanson** [comment]
Does your windows username have a space in it?

**Comment by hafedh-trimeche** [comment]
Yes it has !

**Comment by isaacwhanson** [comment]
Ah yeah.  so your user folder is mounted at `c:\users\{username}\AppData\Swan`, and if your username has a space in it that can be a problem.  I wish I had control of that, but it is a cygwin thing.  I may do some research into a workaround, but I don't have a quick fix for you
