### ISSUE TITLE
Can't install on Windows 10

### ISSUE THREAD

**Issue by gustavo-campo** [starlight/swan-desktop#51]
HI, I'm very interested in being able to run a full Linux desktop without exiting Windows.I've tried several times the Swan installer with no success. It seems from the log that there are problems fetching the necessary files.

2018/01/11 16:50:52 Starting cygwin install, version 2.884
2018/01/11 16:50:52 User has NO backup/restore rights
2018/01/11 16:50:52 io_stream_cygfile: fopen(/etc/setup/setup.rc) failed 2 No such file or directory
2018/01/11 16:50:52 Current Directory: C:\Users\gustavo\AppData\Local\Temp\is-C6Q2C.tmp
2018/01/11 16:50:52 Could not open Service control manager
2018/01/11 16:50:52 root: C:\ProgramData\Swan user
2018/01/11 16:50:52 Selected local directory: C:\Users\gustavo\AppData\Local\Temp\is-C6Q2C.tmp
2018/01/11 16:50:52 net: IE5
2018/01/11 16:50:52 site: http://cygwin.mirror.constant.com/
2018/01/11 16:50:52 site: http://sirius.starlig.ht/
2018/01/11 16:50:56 HTTP status 404 fetching http://cygwin.mirror.constant.com/x86_64/setup.xz.sig
2018/01/11 16:50:56 mbox note: Unable to get http://cygwin.mirror.constant.com/x86_64/setup.xz.sig from <http://cygwin.mirror.constant.com/>
2018/01/11 16:50:56 unattended_mode is set at mbox: returning default value
2018/01/11 16:51:03 mbox note: Unable to get setup from <http://cygwin.mirror.constant.com/>
2018/01/11 16:51:03 unattended_mode is set at mbox: returning default value
2018/01/11 16:51:03 io_stream_cygfile: fopen(/etc/setup/installed.db) failed 2 No such file or directory
2018/01/11 16:51:03 site: http://cygwin.mirror.constant.com/
2018/01/11 16:51:03 site: http://sirius.starlig.ht/
2018/01/11 16:51:03 HTTP status 404 fetching http://cygwin.mirror.constant.com/x86_64/setup.xz.sig
2018/01/11 16:51:04 mbox note: Unable to get http://cygwin.mirror.constant.com/x86_64/setup.xz.sig from <http://cygwin.mirror.constant.com/>
2018/01/11 16:51:04 unattended_mode is set at mbox: returning default value
2018/01/11 16:51:07 mbox note: Unable to get setup from <http://cygwin.mirror.constant.com/>
2018/01/11 16:51:07 unattended_mode is set at mbox: returning default value
2018/01/11 16:51:08 site: http://cygwin.mirror.constant.com/
2018/01/11 16:51:08 site: http://sirius.starlig.ht/
2018/01/11 16:51:08 HTTP status 404 fetching http://cygwin.mirror.constant.com/x86_64/setup.xz.sig
2018/01/11 16:51:08 mbox note: Unable to get http://cygwin.mirror.constant.com/x86_64/setup.xz.sig from <http://cygwin.mirror.constant.com/>
2018/01/11 16:51:08 unattended_mode is set at mbox: returning default value
2018/01/11 16:51:11 mbox note: Unable to get setup from <http://cygwin.mirror.constant.com/>
2018/01/11 16:51:11 unattended_mode is set at mbox: returning default value
2018/01/11 16:51:11 site: http://cygwin.mirror.constant.com/
2018/01/11 16:51:11 site: http://sirius.starlig.ht/
2018/01/11 16:51:11 HTTP status 404 fetching http://cygwin.mirror.constant.com/x86_64/setup.xz.sig
2018/01/11 16:51:12 mbox note: Unable to get http://cygwin.mirror.constant.com/x86_64/setup.xz.sig from <http://cygwin.mirror.constant.com/>
2018/01/11 16:51:12 unattended_mode is set at mbox: returning default value
2018/01/11 16:51:15 mbox note: Unable to get setup from <http://cygwin.mirror.constant.com/>
2018/01/11 16:51:15 unattended_mode is set at mbox: returning default value
2018/01/11 16:51:15 site: http://cygwin.mirror.constant.com/
2018/01/11 16:51:15 site: http://sirius.starlig.ht/
2018/01/11 16:51:16 HTTP status 404 fetching http://cygwin.mirror.constant.com/x86_64/setup.xz.sig
2018/01/11 16:51:16 mbox note: Unable to get http://cygwin.mirror.constant.com/x86_64/setup.xz.sig from <http://cygwin.mirror.constant.com/>
2018/01/11 16:51:16 unattended_mode is set at mbox: returning default value
2018/01/11 16:51:18 mbox note: Unable to get setup from <http://cygwin.mirror.constant.com/>
2018/01/11 16:51:18 unattended_mode is set at mbox: returning default value
2018/01/11 16:51:19 download/verify error in unattended_mode: out of retries
2018/01/11 16:51:19 note: Installation incomplete.  Check C:\ProgramData\Swan\var\log\setup.log.full for details
2018/01/11 16:51:19 Ending cygwin install

I'd appreciate your help.

**Comment by isaacwhanson** [comment]
looks like the mirror 'cygwin.mirror.constant.com' is missing a .sig file.  That is causing the error.
  http://mirrors.xmission.com/cygwin looks to be working ok, you could try the following until I get the exe updated:

`setup-x86_64.exe -vgBqOn -P swan-desktop -R "C:\ProgramData\Swan" -s ""http://sirius.starlig.ht/"" -s "http://mirrors.xmission.com/cygwin/" -K "http://sirius.starlig.ht/sirius.gpg"`

`

**Comment by gustavo-campo** [comment]
I've been able to install with your suggestion, now I have the Swan Desktop icon and the Swan Console.
I still can't get to the xfc4 Desktop, should I open a new issue?
Thanks in advance.

**Comment by isaacwhanson** [comment]
Yes, please.

**Comment by isaacwhanson** [comment]
The downloadable SwanSetup.exe has been updated to use the different mirror.
