### ISSUE TITLE
Can't get the desktop to run

### ISSUE THREAD

**Issue by gustavo-campo** [starlight/swan-desktop#52]
I've installed Swan in a Windows 10 computer but the Swan Desktop shortcut does nothing, I get no error, simply nothing happens.
I opened the Swan Console and executed the bash part of the shortcut there and I get these messages:

$ exec /usr/bin/startx /etc/X11/xinit/Xsession xfce
xauth: (stdin):2:  unknown command "082e7d62f4977cc999a722592cf9fa46"
xauth: (stdin):3:  unknown command "082e7d62f4977cc999a722592cf9fa46"
xauth: (stdin):4:  unknown command "082e7d62f4977cc999a722592cf9fa46"

gam_server: no process found
Welcome to the XWin X Server
Vendor: The Cygwin/X Project
Release: 1.19.6.0
OS: CYGWIN_NT-10.0 DESKTOP-N2VS3LB 2.9.0(0.318/5/3) 2017-09-12 10:18 x86_64
OS: Windows 10  [Windows NT 10.0 build 16299] (Win64)
Package: version 1.19.6-1 built 2017-12-22

XWin was started with the following command line:

X :0 -multiwindow -multimonitors -resize=randr -notrayicon
 -nokeyhook -unixkill -nowinkill -compositewm -noprimary -retro

(EE) Fatal server error:
(EE) Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.

waiting for X server to begin accepting connections .

After that, a few seconds pass and the console closes.

**Comment by isaacwhanson** [comment]
it says it is already running, I assume you do not see the toolbar?
check your task-manager for running X process and kill them. then delete `/tmp/.X0-lock`.
try the Xfce shortcut again, then wait up to a minute to see if it pops up.  There have been reports of really slow startup times for certain brands of computer.

**Comment by gustavo-campo** [comment]
I'm sorry but I still can't get it to run :-/
The X server process ends itself and there is no .X0-lock file in the tmp folder.
I'm using the latest VcXsrv, should I use Xming or another X server?
I also reinstalled everything just in case.

**Comment by isaacwhanson** [comment]
Swan downloads, installs and runs its own X server, XWin.  If you are running another X server, that could be the issue.  Also, if your other processes make use of cygwin they may cause conflicts while running.
