### ISSUE TITLE
Trouble Installing On windows 10

### ISSUE THREAD

**Issue by youngbloodg** [starlight/swan-desktop#55]
Hi, I can't seem to get it to install properly. I get a Program Data folder, but there's no Swan XCFE desktop application or Shortcut. Attached are my logs, many thanks!
[setup.log](https://github.com/starlight/swan-desktop/files/1760201/setup.log)

**Comment by isaacwhanson** [comment]
it looks like none of the starlig.ht packages were downloaded or installed.  perhaps the cygwin guys made a breaking change.  will investigate

**Comment by isaacwhanson** [comment]
that seems to be exactly what happened. I will have to file an upstream bug report, and look for a work-around in the mean time.

**Comment by terryweiss** [comment]
I just was hit by this after a fresh windows install. Is there a way to complete the install manually? Would some variation on the setup found [here](https://github.com/starlight/swan-desktop/issues/26) help? I think if I could just locate `spm` I'd be ok. Any guidance?

**Comment by isaacwhanson** [comment]
working on this right now actually.  not sure what the cause is yet

**Comment by isaacwhanson** [comment]
All fixed now.  turned out a dependency got removed `mate-dialogs` and the new cygwin setup will not install packages with missing dependencies (`swan-desktop` in this case).  I have replaced `mate-dialogs` with `zenity` and everything is happy again.
