### ISSUE TITLE
Error when trying to use spm

### ISSUE THREAD

**Issue by EFugier** [starlight/swan-desktop#57]
Context: a fresh install of windows 10, Swan was the first program I installed.

For instance, `spm -u` gives

> Unable to start 'C:\Users\XXX\AppData\Roaming\Swan\.cache\spm\setup-x86_64.exe': The operating system denied access to the specified file.

Starting the Swan console in admin mode doesn't help either !

**Comment by isaacwhanson** [comment]
Hmm, there should be a "\" between Swan and .cache, is that accurate?

**Comment by EFugier** [comment]
Sorry, messed up the copy paste, the path in the error message is correct !

**Comment by isaacwhanson** [comment]
* When you say the error message is correct, do you mean that the error message says `Swan.cache` or `Swan\.cache`?
* is your Windows 64-bit?
* Does the `setup-x86_64.exe` exist at that path?
* Does the `setup-x86_64.exe` file have executable permissions (see output of `ls -l`)?  Does it run if you double-click it?
* What kind of machine is it? Is it a Lenovo ThinkPad for example?
* Are you running any antivirus? sometimes a false-alert is raised with the Cygwin exe.

**Comment by EFugier** [comment]
* The file do exist and the error message says `Swan\.cache`.
* It has the executable permission.
* When I double click it says:  
> This app can't run on your PC, to find a version for your PC, check with the publisher
* It is a dell Latitude E7380
* Only windows defender is running, but the commands other than spm do work just fine !

**Comment by EFugier** [comment]
`uname -m` gives `x86_64`.

I am currently performing a system scan and will try 2, 3 and 4 as soon as it finishes.

**Comment by isaacwhanson** [comment]
if it doesn't work, please tell me the size of the file downloaded (should be about 1.07 MB)

**Comment by EFugier** [comment]
The current `setup-x86_64.exe` size is 915 bytes.

**Comment by EFugier** [comment]
It works now !
Steps to solve the problem:
1. delete the `setup-x86_64.exe` file
2. run `spm -u`

I don't know what caused the bug though.

**Comment by isaacwhanson** [comment]
`spm` will always check for an update to `setup-x86_64.exe` and download it if there is a newer one (or if you don't have the file) from the official Cygwin website.

There must have been a problem with the download the first time, either a problem with the Cygwin website, or your network connection.  This caused a corrupt exe file.

Glad you are working now, please enjoy!

**Comment by EFugier** [comment]
Thanks a lot, be sure that I'll enjoy that awesome piece of software you wrote as I did for quite some time now !
