### ISSUE TITLE
Swan does not have a silent cygwin install

### ISSUE THREAD

**Issue by jordwalke** [starlight/swan-desktop#59]
I noticed that Swan now pops up a dialog asking where to install the Cygwin cache. Did it always do this? Is it possible to make it silent?

**Comment by isaacwhanson** [comment]
I am unable to reproduce that here.  Could I get a screenshot of that dialog?

**Comment by jordwalke** [comment]
I don't have it anymore but it was just the standard cygwin install dialog that tells you it's downloading sources etc.
