### ISSUE TITLE
Offline setup option

### ISSUE THREAD

**Issue by vijaysg** [starlight/swan-desktop#9]
Hi,
 Looks great! Thank you.
It would be helpful to have an option to create offline installation image through the current setup file for installing/testing on offline networks.

**Comment by ivdok** [comment]
You can just copy the repo from starlig.ht and add it locally to the Cygwin
installer.

**Comment by isaacwhanson** [comment]
You can make an archive of the installation folder (`C:\.swan-x86_64` by default) and extract it to the destination.  Be sure to grab the shortcuts too.  It doesn't require any registry entries or anything.  You may want to clear the cache before creating the archive using `spm -c`.  @ivdok 's suggestion would also work, but is a bit more involved.
